### ISSUE TITLE
Smile.Amazon.com

### ISSUE THREAD

**Issue by icdmize** [biscoe916/Reddit-Hot-Swap#3]
Everytime I try to go to Amazon.com it tries to redirect to Smile.Amazon.com and 404s.

**Comment by biscoe916** [comment]
@icdmize That was intentional as smile.amazon.com behaves in exactly the same way as amazon.com only a portion of your purchase is donated to a charity of your choice. It's bugged, though. It was a mistake to put this in without vetting it with users of the extension, and without thorough testing. I apologize. I'm unable to address the issue and likely won't have the time for a few weeks. It's an extremely simple fix, however, and I would be happy to approve a PR should someone submit one.

**Comment by biscoe916** [comment]
@icdmize Actually this has already been fixed. I just need to deploy the fix to the the chrome/firefox store.
